spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meumoneyapi?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root  jpa:    show-sql: true
      jackson:    deserialization:      fail-on-unknown-properties: true